### ISSUE TITLE
Bug. Short transcripts length bug

### ISSUE THREAD

**Issue by LucasSilvaFerreira** [WGLab/lncScore#3]
Hi!
I found some transcripts with short length returning a error in script 

The 8 length transcript returns an error.
How long should be the transcript for the program to be able to make a reliable prediction?

Transcript_name  seq_len

> ENST00000415118.1 8
> Traceback (most recent call last):
>   File "scripts/lncScore/lncScore.py", line 489, in <module>
>     mainProcess(ARRAY,outPutFileName,1,coding,noncoding,Alphabet,Matrix_hash,classifier)
>   File "/scripts/lncScore/lncScore.py", line 333, in mainProcess
>     (MCS,CSL,CP) = mcssProcess(tran_sec_seq2,c_tab,g_tab)
>   File "/scripts/lncScore/lncScore.py", line 234, in mcssProcess
>     CodingPercent = MaxCodingScore/float(TotalCodingScore)
> ZeroDivisionError: float division by zero

Thanks
Lucas F Silva

**Comment by zhaodoctor** [comment]
Hi,
Because lncRNA is roughly defined as ncRNA longer than 200nt, so in lncScore the input transcript should be longer than 200nt.
Thanks.

**Comment by kaichop** [comment]
Jian, please change the code to handle this situation and exclude the
transcripts. You cannot expect users to know this and do these filterings
beforehand.

**Comment by zhaodoctor** [comment]
Ok, for transripts shorter than 200nt, I will output the error message for users.
Thanks.

发自我的 iPhone

**Comment by kvittingseerup** [comment]
Why would you prevent scoring of shorter transcripts - i guess they would just get a low score - in that way you could avoid the assumption?

**Comment by zhaodoctor** [comment]
In fact, for transcripts (len < 200), it also can be calcualted and the score would be low. However, the transcripts with length < 200 are commonly classified as small RNAs. Tanscripts with length >200 are commonly classified as lncRNAs.
And for those transcripts which are too short (<10 or 20), the program would be more possbilely cutted (or stopped) by feature calculation error (just like the problem LucasSilvaFerreira met, 'float division by zero').
